name: Duster Lint

on:
    pull_request:
        branches: [ master ]

jobs:
  duster:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      - name: Composer Install
        run: composer install
      - name: "Duster Lint"
        run: ./vendor/bin/duster lint

